export const CHAPTERS = [
  {
    id: "chapel",
    number: "01",
    name: "Desecrated Chapel",
    description: "Reclaim the altar. Make the unholy kneel.",
    objective: "Follow the corridor and find the desecrated chapel.",
  },
  {
    id: "armory",
    number: "02",
    name: "The Armory",
    description: "Ancient faith. Modern firepower.",
    objective: "Search the armory and collect the blessed weapons.",
  },
  {
    id: "laboratory",
    number: "03",
    name: "Laboratory Complex",
    description: "Discover what they brought back.",
    objective: "Find the security keycards and reach the exit.",
  },
  {
    id: "containment",
    number: "04",
    name: "Containment Area",
    description: "Some things were never meant to escape.",
    objective:
      "Restore containment systems and activate the emergency protocol.",
  },
  {
    id: "tunnels",
    number: "05",
    name: "Tunnel Network",
    description: "The only way out is further down.",
    objective: "Explore the tunnel network and find a way through.",
  },
  {
    id: "spawning",
    number: "06",
    name: "Spawning Grounds",
    description: "Cut the invasion off at its source.",
    objective: "Find and destroy the demonic spawning pools.",
  },
  {
    id: "observatory",
    number: "07",
    name: "Observatory",
    description: "Something is looking back.",
    objective: "Explore the observatory and secure the tower.",
  },
  {
    id: "communications",
    number: "08",
    name: "Communications Tower",
    description: "A last transmission from the damned.",
    objective: "Restore communications and transmit the warning.",
  },
  {
    id: "reactor",
    number: "09",
    name: "Reactor Core",
    description: "Faith burns brighter than the core.",
    objective: "Stabilize the reactor and stop the meltdown.",
  },
  {
    id: "finalarena",
    number: "10",
    name: "Final Arena",
    description: "Finish what resurrection started.",
    objective: "Confront the final threat and close the portal.",
  },
  {
    id: "archive",
    number: "SECRET",
    name: "Forbidden Archive",
    description: "The truth was buried for a reason.",
    objective: "Explore the forbidden archive and uncover its secrets.",
  },
  {
    id: "techfacility",
    number: "SECRET",
    name: "Black Site Omega",
    description: "Their greatest weapon. Their worst mistake.",
    objective: "Investigate the black site and recover its technology.",
  },
  {
    id: "tutorial",
    number: "PROLOGUE",
    name: "Vatican Inquisition",
    description: "Meet your handlers. Remember your training.",
    objective: "Listen to the Inquisitor and complete your training.",
  },
];
export const getChapter = (id) => CHAPTERS.find((chapter) => chapter.id === id);
