export interface Word {
  id: string;
  label: string;
  emoji: string;
  tier: number;
}

export const INITIAL_WORDS: Word[] = [
  { id: 'matter', label: 'Matter', emoji: '🌑', tier: 0 },
  { id: 'energy', label: 'Energy', emoji: '⚡', tier: 0 },
  { id: 'space', label: 'Space', emoji: '🌌', tier: 0 },
  { id: 'time', label: 'Time', emoji: '⏳', tier: 0 },
];

export const RECIPES: Record<string, string> = {
  'matter+energy': 'plasma',
  'energy+matter': 'plasma',
  'matter+matter': 'rock',
  'energy+energy': 'light',
  'space+time': 'velocity',
  'time+space': 'velocity',
  'velocity+matter': 'momentum',
  'matter+velocity': 'momentum',
  'rock+energy': 'magma',
  'energy+rock': 'magma',
  'magma+time': 'rock',
  'rock+rock': 'mountain',
  'light+energy': 'radiation',
  'energy+light': 'radiation',
  'matter+light': 'shadow',
  'light+matter': 'shadow',
  'space+matter': 'planet',
  'matter+space': 'planet',
  'planet+energy': 'life',
  'energy+planet': 'life',
  'life+time': 'evolution',
  'time+life': 'evolution',
  'evolution+matter': 'human',
  'matter+evolution': 'human',
  'human+energy': 'fire',
  'energy+human': 'fire',
  'fire+matter': 'metal',
  'matter+fire': 'metal',
  'metal+energy': 'electricity',
  'energy+metal': 'electricity',
  'human+time': 'wisdom',
  'time+human': 'wisdom',
  'wisdom+metal': 'technology',
  'metal+wisdom': 'technology',
  'technology+energy': 'computer',
  'energy+technology': 'computer',
  'computer+wisdom': 'ai',
  'wisdom+computer': 'ai',
  'human+human': 'society',
  'society+technology': 'city',
  'city+energy': 'metropolis',
  'metropolis+ai': 'singularity',
  'rock+life': 'moss',
  'moss+time': 'grass',
  'grass+life': 'animal',
  'animal+time': 'human',
  'metal+electricity': 'robot',
  'robot+ai': 'android',
  'life+electricity': 'frankenstein',
};

export const ALL_WORDS: Record<string, Word> = {
  ...Object.fromEntries(INITIAL_WORDS.map(w => [w.id, w])),
  plasma: { id: 'plasma', label: 'Plasma', emoji: '🔥', tier: 1 },
  rock: { id: 'rock', label: 'Rock', emoji: '🪨', tier: 1 },
  light: { id: 'light', label: 'Light', emoji: '✨', tier: 1 },
  velocity: { id: 'velocity', label: 'Velocity', emoji: '🏃', tier: 1 },
  momentum: { id: 'momentum', label: 'Momentum', emoji: '🌠', tier: 2 },
  magma: { id: 'magma', label: 'Magma', emoji: '🌋', tier: 2 },
  mountain: { id: 'mountain', label: 'Mountain', emoji: '⛰️', tier: 2 },
  radiation: { id: 'radiation', label: 'Radiation', emoji: '☢️', tier: 2 },
  shadow: { id: 'shadow', label: 'Shadow', emoji: '👤', tier: 2 },
  planet: { id: 'planet', label: 'Planet', emoji: '🪐', tier: 2 },
  life: { id: 'life', label: 'Life', emoji: '🌱', tier: 3 },
  evolution: { id: 'evolution', label: 'Evolution', emoji: '🧬', tier: 4 },
  human: { id: 'human', label: 'Human', emoji: '🧔', tier: 5 },
  fire: { id: 'fire', label: 'Fire', emoji: '🔥', tier: 6 },
  metal: { id: 'metal', label: 'Metal', emoji: '⛓️', tier: 7 },
  electricity: { id: 'electricity', label: 'Electricity', emoji: '🔌', tier: 8 },
  wisdom: { id: 'wisdom', label: 'Wisdom', emoji: '📖', tier: 6 },
  technology: { id: 'technology', label: 'Technology', emoji: '🛠️', tier: 9 },
  computer: { id: 'computer', label: 'Computer', emoji: '💻', tier: 10 },
  ai: { id: 'ai', label: 'AI', emoji: '🤖', tier: 11 },
  society: { id: 'society', label: 'Society', emoji: '🏘️', tier: 6 },
  city: { id: 'city', label: 'City', emoji: '🏙️', tier: 10 },
  metropolis: { id: 'metropolis', label: 'Metropolis', emoji: '🌆', tier: 11 },
  singularity: { id: 'singularity', label: 'Singularity', emoji: '🌌', tier: 12 },
  moss: { id: 'moss', label: 'Moss', emoji: '🌿', tier: 2 },
  grass: { id: 'grass', label: 'Grass', emoji: '🌱', tier: 3 },
  animal: { id: 'animal', label: 'Animal', emoji: '🦌', tier: 4 },
  robot: { id: 'robot', label: 'Robot', emoji: '🤖', tier: 9 },
  android: { id: 'android', label: 'Android', emoji: '🤖', tier: 12 },
  frankenstein: { id: 'frankenstein', label: 'Frankenstein', emoji: '🧟', tier: 4 },
};